inherit_gem:
  ruboconf: ruboconf.yml
AllCops:
  TargetRubyVersion: 2.6
  inherit_mode:
    merge:
      - Exclude
  Exclude:
    - 'data/**/*'
    - 'test/schema.rb'
    - 'bin/**/*'
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/**/*'
Style/GlobalVars:
  Exclude:
    - 'benchmarks/**/*'
