# Taken from https://github.com/actions/starter-workflows/blob/08ff79c7b930315861d16bed4903ddd90bf7c05c/ci/ruby.yml
name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ '3.1', '3.2', '3.3', head, truffleruby, jruby ]
        db_adapter: [ sqlite, mysql, postgresql ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: mv test/database.yml.example test/database.yml
      - run: mv docker-compose.yml.example docker-compose.yml
        if: ${{ matrix.db_adapter == 'mysql' || matrix.db_adapter == 'postgresql' }}
      - run: docker-compose up -d ${{ matrix.db_adapter }}
        if: ${{ matrix.db_adapter == 'mysql' || matrix.db_adapter == 'postgresql' }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: DB=${{ matrix.db_adapter }} bundle exec rake
        continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
